spring.application.name=servicio-usuarios
server.port=8081

jwt.secret=SicaeProyectoFinalTecnologiaParaLaIntegracion2026


spring.datasource.url=jdbc:postgresql://localhost:5432/sicaeUsuario
spring.datasource.username=postgres
spring.datasource.password=hachy200
spring.datasource.driver-class-name=org.postgresql.Driver

mybatis.mapper-locations=classpath:mappers/*.xml
mybatis.type-aliases-package=mx.uv.sicae.servicio_usuarios.modelo