spring.application.name=servicio-usuarios
# Puerto donde correr\u00e1 este microservicio
server.port=8081

# Conexi\u00f3n a la base de datos de PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/usuarios
spring.datasource.username=postgres
spring.datasource.password=hachy200
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuraci\u00f3n de MyBatis para encontrar los archivos XML de SQL
mybatis.mapper-locations=classpath:mappers/*.xml
mybatis.type-aliases-package=mx.uv.sicae.usuarios.modelo